name: Build and Deploy to Netlify

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - uses: actions/checkout@v2
      - name: "Create env file"
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VITE_FRONTEND_VERSION: $(node -p "require('./package.json').version")"
          file_name: .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm build:web

      - name: Run the tests and generate coverage report
        run: pnpm test -- --coverage

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0

      - name: Netlify Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir "./packages/web/build"
